---
name: "Paperpile"
platform: "__PLATFORM__"

paperpile_user_dir: "__PP_USER_DIR__"
user_settings_db: "__PP_USER_DIR__/settings.db"
queue_db: "__PP_USER_DIR__/tmp/queue.db"

Model::App:
  dsn: "dbi:SQLite:__path_to(db/app.db)__"

Model::User:
  dsn: "dbi:SQLite:__PP_USER_DIR__/settings.db"

Model::Queue:
  dsn: "dbi:SQLite:__PP_USER_DIR__/tmp/queue.db"

session:
  storage: "__PP_USER_DIR__/tmp/session"

app_settings:
  platform: "__PLATFORM__"
  version_id: 2
  version_string: "0.4.1-preview"
  build_number: 0

user_settings:
  tmp_dir: "__PP_USER_DIR__/tmp"
  library_db: "__PP_USER_DIR__/paperpile.ppl"
  user_home: "__USERHOME__"
  use_proxy: ""
  proxy: ""
  proxy_user: ""
  proxy_passwd: ""
  pager_limit: 25
  _queue: ""

library_settings:
  paper_root: "__PP_USER_DIR__/papers"
  key_pattern: "[firstauthor][YYYY]"
  pdf_pattern: "[key]"
  attachment_pattern: "[key]_supplements"
  search_seq: "PubMed"
  _tree: ""
