---
name: "Paperpile"
platform: "__PLATFORM__"

paperpile_user_dir: "__PP_USER_DIR__"
user_settings_db: "__PP_USER_DIR__/settings.db"
queue_db: "__PP_USER_DIR__/tmp/queue.db"

Model::App:
  dsn: "dbi:SQLite:__path_to(db/app.db)__"

Model::User:
  dsn: "dbi:SQLite:__PP_USER_DIR__/settings.db"

Model::Queue:
  dsn: "dbi:SQLite:__PP_USER_DIR__/tmp/queue.db"

session:
  storage: "__PP_USER_DIR__/tmp/session"
  expires: 100000000

app_settings:
  platform: "__PLATFORM__"
  version_id: 4
  version_name: "0.4.3"
  build_number: 0
  settings_db_version: 1
  library_db_version: 2
  titanium_version: 1.0.0

user_settings:
  db_version: 1
  tmp_dir: "__PP_USER_DIR__/tmp"
  library_db: "__PP_USER_DIR__/paperpile.ppl"
  user_home: "__USERHOME__"
  file_sync: ""
  use_proxy: ""
  proxy: ""
  proxy_user: ""
  proxy_passwd: ""
  pager_limit: 25
  zoom_level: "100%"
  tags_list_height: 120
  _queue: ""

library_settings:
  db_version: 2
  paper_root: "__PP_PAPER_DIR__"
  key_pattern: "[Firstauthor][YYYY]"
  pdf_pattern: "[key]"
  attachment_pattern: "[key]_supplements"
  search_seq: "PubMed,GoogleScholar"
  bibtex:
    bibtex_mode: 0
    import_strip_tex: 1
    export_escape: 1
    pretty_print: 1
    use_quotes: 0
    double_dash: 1
    title_quote_complete: 0 
    title_quote_smart: 1 
    title_quote:
      - DNA
      - RNA
      - CERN
    export_fields:
      abstract: 1
      affiliation: 0
      eprint: 0
      issn: 0
      isbn: 0
      pmid: 1
      lccn: 0
      doi: 1
      keywords: 0 
  _tree: ""

release:
  patch: 1
  restart: 1
  msg: "Several improvements and many bug-fixes for the public Linux beta."
  log:
    - "Improved automatic PDF download (especially for some Physics Journals)"
    - "Improved PDF meta-data recognition (many of the PDFs you reported now work)"
    - "Streamlined data input for PDFs that cannot not be automatically imported"
    - "Allow re-ordering of label list and RSS feed list"
    - "More efficient way to display and search RSS feeds"
    - "Allow cancel of searches (e.g. when PubMed is down or slow)"
    - "27 additional bugfixes (thanks for all the error reports)" 
