---
name: "Paperpile"
platform: "__PLATFORM__"

paperpile_user_dir: "__PP_USER_DIR__"
user_settings_db: "__PP_USER_DIR__/settings.db"

tmp_dir: "__PP_TMP_DIR__"
queue_db: "__PP_TMP_DIR__/queue.db"

Model::App:
  dsn: "dbi:SQLite:__path_to(db/app.db)__"

Model::User:
  dsn: "dbi:SQLite:__PP_USER_DIR__/settings.db"

Model::Queue:
  dsn: "dbi:SQLite:__PP_TMP_DIR__/queue.db"

app_settings:
  platform: "__PLATFORM__"
  version_id: 5
  version_name: "0.5"
  build_number: 0
  settings_db_version: 2
  library_db_version: 3
  qruntime_version: 1
  paperserve_url: "http://s.paperpile.com"

user_settings:
  db_version: 2
  library_db: "__PP_USER_DIR__/paperpile.ppl"
  user_home: "__USERHOME__"
  file_sync: ""
  use_proxy: ""
  proxy: ""
  proxy_user: ""
  proxy_passwd: ""
  pager_limit: 25
  check_updates: 1
  font_size: Normal
  split_fraction_tree: 0.2
  split_fraction_grid: 0.67

library_settings:
  db_version: 3
  paper_root: "__PP_PAPER_DIR__"
  key_pattern: "[Firstauthor][YYYY]"
  pdf_pattern: "[key]"
  attachment_pattern: "[key]_supplements"
  search_seq: "PubMed,GoogleScholar"
  sort_field: "created DESC"
  bibtex:
    bibtex_mode: 0
    import_strip_tex: 1
    export_escape: 1
    pretty_print: 1
    use_quotes: 0
    cite_wrap: 1
    double_dash: 1
    title_quote_complete: 0 
    title_quote_smart: 1 
    title_quote:
      - DNA
      - RNA
      - CERN
    export_fields:
      abstract: 0
      affiliation: 0
      eprint: 0
      issn: 0
      isbn: 0
      pmid: 1
      lccn: 0
      doi: 1
      keywords: 0 
  _tree: ""

release:
  patch: 0
  restart: 1
  msg: "Major update with many more features."
  log:
    - "Streamlined user interface including native file open/save dialogs"
    - "Advanced BibTeX support with improved import/export and citation functions"
    - "Auto-export of folder or labels to BibTeX files"
    - "Improved import functions. Import your references including tags and PDFs from various other programs"
    - "Drag and drop support. Drag PDFs, attachments or library files directly into Paperpile"
    - "Improved workflow to import PDFs"
    - "Smart online lookup to auto-complete partial references"
    - "Keyboard shortcuts for all major functions"
